### ISSUE TITLE
Support vim-mode-plus

### ISSUE THREAD

**Issue by ypresto** [aki77/atom-vim-mode-clipboard-plus#1]
https://github.com/t9md/atom-vim-mode-plus

vim-mode-plus uses different namespace, and this plugin is listed in unsupported plugins.

For workaround paste below snippet in init script.

``` coffee
atom.commands.add 'atom-text-editor.vim-mode-plus:not(.insert-mode)', 'vim-mode:put-after', (event) ->
  atom.commands.dispatch event.target, 'vim-mode-plus:put-after'
```

(Requires "Use Clipboard As Default Register" of vim-mode-plus to be enabled.)

**Comment by aki77** [comment]
Added `useVimModePlus` settings.

**Comment by ypresto** [comment]
It worked!! :tada: Thanks!

**Comment by aki77** [comment]
:smiley:

**Comment by zhengwy888** [comment]
I am using vim-mode-plus but there is no popup when I press 'ctrl-p'. I am using macos. what could go wrong? the menu option for clipboard plus:toggle works.
